target_sources(binaryninjaapi PRIVATE
    activity.cpp
    architecture.cpp
    backgroundtask.cpp
    basedetection.cpp
    basicblock.cpp
    binaryninjaapi.cpp
    binaryreader.cpp
    binaryview.cpp
    binaryviewtype.cpp
    binarywriter.cpp
    callingconvention.cpp
    collaboration.cpp
    component.cpp
    database.cpp
    databuffer.cpp
    datarenderer.cpp
    debuginfo.cpp
    demangle.cpp
    downloadprovider.cpp
    enterprise.cpp
    exceptions.cpp
    externallibrary.cpp
    ffi.cpp
    fileaccessor.cpp
    filemetadata.cpp
    firmwareninja.cpp
    flowgraph.cpp
    flowgraphlayout.cpp
    flowgraphnode.cpp
    function.cpp
    functionrecognizer.cpp
    highlevelil.cpp
    highlevelilinstruction.cpp
    http.cpp
    interaction.cpp
    languagerepresentation.cpp
    linearviewcursor.cpp
    linearviewobject.cpp
    lineformatter.cpp
    log.cpp
    lowlevelil.cpp
    lowlevelilinstruction.cpp
    mainthread.cpp
    mediumlevelil.cpp
    mediumlevelilinstruction.cpp
    metadata.cpp
    platform.cpp
    plugin.cpp
    pluginmanager.cpp
    project.cpp
    relocationhandler.cpp
    renderlayer.cpp
    scriptingprovider.cpp
    secretsprovider.cpp
    settings.cpp
    tempfile.cpp
    transform.cpp
    type.cpp
    typearchive.cpp
    typecontainer.cpp
    typelibrary.cpp
    typeparser.cpp
    typeprinter.cpp
    undoaction.cpp
    unicode.cpp
    update.cpp
    user.cpp
    websocketprovider.cpp
    workflow.cpp
)
# Vendored (and modified) JsonCpp source
target_sources(binaryninjaapi PRIVATE json/jsoncpp.cpp)
