name: Build

on:
  push:
    branches: ["cmake-refactor"]
  pull_request:
    branches: ["cmake-refactor"]

jobs:
  build:
    name: build (${{matrix.config.os}}, ${{ matrix.headless == 'ON' && 'headless' || 'ui' }})
    runs-on: ${{matrix.config.os}}
    env:
      UI_TYPE: ${{ matrix.headless == 'ON' && 'headless' || 'ui' }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: windows-2022,
             name: windows,
             cmake_j: "-- /p:CL_MPcount=4"}
          - {os: macos-15,
             name: macos,
             cmake_j: "-j 4"}
          - {os: ubuntu-24.04,
             name: ubuntu,
             cmake_j: "-j 4"}
        headless:
          - "ON"
          - "OFF"
        include:
          - config: {name: macos}
            cmakeVersion: latest
          - config: {name: ubuntu}
            headless: "ON"
            cmakeVersion: ~3.14.0
          - config: {name: ubuntu}
            headless: "OFF"
            # Qt requires at least CMake 3.16.0
            cmakeVersion: ~3.16.0
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Get CMake
        if: ${{ matrix.config.name != 'windows' }}
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: ${{ matrix.cmakeVersion }}

      - uses: ilammy/msvc-dev-cmd@v1

      - name: Install Vector 35 Qt6
        if: ${{ matrix.headless == 'OFF' }}
        shell: bash
        run: |
          QT_VER=6.8.2
          QT_INSTALL="$GITHUB_WORKSPACE"

          if [ "${{ matrix.config.name }}" == "windows" ]; then
            echo "Installing Qt6 for Windows"
            curl -L -o qt6.zip "https://github.com/Vector35/qt-artifacts/releases/download/$QT_VER/qt$QT_VER-win64.zip"
            7z x qt6.zip -o"$QT_INSTALL"
            QT_INSTALL="$QT_INSTALL/Qt/$QT_VER/msvc2022_64"
          elif [ "${{ matrix.config.name }}" == "macos" ]; then
            echo "Installing Qt6 for macOS"
            curl -L -o qt6.zip "https://github.com/Vector35/qt-artifacts/releases/download/$QT_VER/qt$QT_VER-macosx.zip"
            unzip qt6.zip -d "$QT_INSTALL"
            QT_INSTALL="$QT_INSTALL/Qt/$QT_VER/clang_64"
          elif [ "${{ matrix.config.name }}" == "ubuntu" ]; then
            sudo apt-get update -y
            # Need to install qt6-base-dev to get dependencies
            sudo apt-get install -y qt6-base-dev
            echo "Installing Qt6 for Ubuntu"
            curl -L -o qt6.zip "https://github.com/Vector35/qt-artifacts/releases/download/$QT_VER/qt$QT_VER-linux.zip"
            unzip qt6.zip -d "$QT_INSTALL"
            QT_INSTALL="$QT_INSTALL/Qt/$QT_VER/gcc_64"
          else
            echo "Unsupported OS: ${{ matrix.config.name }}"
            exit 1
          fi
          echo "Qt6 extracted to $QT_INSTALL"
          rm qt6.zip
          
          QT_CMAKE="$QT_INSTALL/lib/cmake/Qt6"
          ls -la "$QT_CMAKE"

          echo "QT_CMAKE=-DQt6_DIR=$QT_CMAKE" >> "$GITHUB_ENV"

      - name: Configure binaryninjaapi
        run: cmake -B build -S .
              -DCMAKE_BUILD_TYPE=RelWithDebInfo
              -DCMAKE_INSTALL_PREFIX=install
              -DBinaryNinjaAPI_HEADLESS=${{matrix.headless}}
              ${{ env.QT_CMAKE }}

      - name: Build binaryninjaapi
        run: cmake --build build
              --config RelWithDebInfo
              ${{ matrix.config.cmake_j }}

      - name: Install binaryninjaapi
        run: cmake --build build
              --config RelWithDebInfo
              --target install

      - name: Upload binaryninjaapi artifact
        # Installed binaryninjaapi works regardless of headless mode
        if: ${{ matrix.headless == 'ON' }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{matrix.config.name}}-${{env.UI_TYPE}}-binaryninjaapi
          path: install/

      - name: Configure Everything Else
        run: cmake -B build -S .
              -DBinaryNinjaAPI_BUILD_EXAMPLES=ON
              -DBinaryNinjaAPI_USER_PLUGINS_DIR=install-user-plugins

      - name: Build Everything Else
        run: cmake --build build
              --config RelWithDebInfo
              ${{ matrix.config.cmake_j }}

      - name: Install Everything Else (CMake 3.15.0+)
        if: ${{ matrix.cmakeVersion != '~3.14.0' }}
        run: cmake --install build
              --config RelWithDebInfo
              --component BinaryNinjaUserPlugin
      - name: Install Everything Else (CMake 3.14)
        if: ${{ matrix.cmakeVersion == '~3.14.0' }}
        run: cmake -DCOMPONENT=BinaryNinjaUserPlugin
              -P build/cmake_install.cmake

      - name: Upload binaryninjaapi artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{matrix.config.name}}-${{env.UI_TYPE}}-user-plugins
          path: install-user-plugins/

      - name: Cleanup build directory
        shell: bash
        run: rm -rf build

      - name: Configure examples against installed API
        run: cmake -B build-installed -S examples
              -DCMAKE_BUILD_TYPE=RelWithDebInfo
              -DCMAKE_INSTALL_PREFIX=install
              -DBinaryNinjaAPI_HEADLESS=${{matrix.headless}}
              ${{ env.QT_CMAKE }}

      - name: Build examples against installed API
        run: cmake --build build-installed
              --config RelWithDebInfo
              ${{ matrix.config.cmake_j }}
